apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-aggregator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-aggregator
  template:
    metadata:
      labels:
        app: gateway-aggregator
    spec:
      containers:
      - name: gateway-aggregator
        image: custom-services/gateway-aggregator
        imagePullPolicy: Never
        ports:
          - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-aggregator-service
spec:
  selector:
    app: gateway-aggregator
  ports:
  - port: 80
    targetPort: 8000
  type: NodePort
  