apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: s3
  namespace: default
  labels:
    zone: default
    app: s3
    version: "1.0"
  annotations:
    something: something
spec:
  selector:
    matchLabels:
      app: s3
  replicas: 1
  
  template:
    metadata:
      labels:
        zone: default
        app: s3
        version: "1.0"
        prometheus.io/scrape: 'true'
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
    spec:
      terminationGracePeriodSeconds : 3
      #schedulerName: no-balancing-scheduler
      containers:
        - name: s3
          image: wmeijer221/microservice_v4-screen:latest
          ports:
            - name: http-mubpodport
              containerPort: 8080
          volumeMounts:
            - name: podinfo
              mountPath: /etc/podinfo
            - name: microservice-workmodel
              mountPath: /app/MSConfig
            - name: microservice-internal-services
              mountPath: /app/MSConfig/InternalServiceFunctions
          env:
            - name: APP
              value: s3
            - name: ZONE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['zone']
            - name: K8S_APP
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app']
            - name: PN
              value: '1'
            - name: TN
              value: '1'
          resources: {}    
        
        

      

      volumes:
        - name: podinfo
          downwardAPI:
            items:
              - path: "labels"
                fieldRef:
                  fieldPath: metadata.labels
              - path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations
        - name: microservice-workmodel
          configMap:
            name: workmodel
        - name: microservice-internal-services
          configMap:
            name: internal-services        
---
apiVersion: v1
kind: Service
metadata:
  name: s3
  namespace: default
  labels:
    app: s3
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort:
    name: http-mubserviceport
  - port: 51313
    targetPort: 51313
    name: grpc-mubserviceport
  selector:
    app: s3